// Generated by `pnpm --filter @internradar/db types:write`. Do not edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "app_admins": {
                  Row: {
                    "user_id": string
                  }
                  Insert: {
                    "user_id": string
                  }
                  Update: {
                    "user_id"?: string
                  }
                  Relationships: [
                    
                  ]
                },"application_events": {
                  Row: {
                    "application_id": string,"from_status": Database["public"]['Enums']["app_status"] | null,"id": number,"is_undo": boolean,"occurred_at": string,"resume_id": string | null,"to_status": Database["public"]['Enums']["app_status"],"user_id": string
                  }
                  Insert: {
                    "application_id": string,"from_status"?: Database["public"]['Enums']["app_status"] | null,"id"?: never,"is_undo"?: boolean,"occurred_at"?: string,"resume_id"?: string | null,"to_status": Database["public"]['Enums']["app_status"],"user_id": string
                  }
                  Update: {
                    "application_id"?: string,"from_status"?: Database["public"]['Enums']["app_status"] | null,"id"?: never,"is_undo"?: boolean,"occurred_at"?: string,"resume_id"?: string | null,"to_status"?: Database["public"]['Enums']["app_status"],"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "application_events_application_id_user_id_fkey"
      columns: ["application_id","user_id"]
isOneToOne: false
      referencedRelation: "applications"
      referencedColumns: ["id","user_id"]
    }
                  ]
                },"applications": {
                  Row: {
                    "applied_at": string | null,"created_at": string,"cycle_year": number,"id": string,"notes": string | null,"program_id": string,"program_window_id": string | null,"resume_id": string | null,"status": Database["public"]['Enums']["app_status"],"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "applied_at"?: string | null,"created_at"?: string,"cycle_year": number,"id"?: string,"notes"?: string | null,"program_id": string,"program_window_id"?: string | null,"resume_id"?: string | null,"status"?: Database["public"]['Enums']["app_status"],"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "applied_at"?: string | null,"created_at"?: string,"cycle_year"?: number,"id"?: string,"notes"?: string | null,"program_id"?: string,"program_window_id"?: string | null,"resume_id"?: string | null,"status"?: Database["public"]['Enums']["app_status"],"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "applications_program_id_fkey"
      columns: ["program_id"]
isOneToOne: false
      referencedRelation: "programs"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "applications_resume_id_user_id_fkey"
      columns: ["resume_id","user_id"]
isOneToOne: false
      referencedRelation: "resumes"
      referencedColumns: ["id","user_id"]
    },{
      foreignKeyName: "applications_window_matches_program"
      columns: ["program_window_id","program_id"]
isOneToOne: false
      referencedRelation: "program_windows"
      referencedColumns: ["id","program_id"]
    }
                  ]
                },"ats_fetches": {
                  Row: {
                    "ats_source_id": string,"error": string | null,"fetch_day": string,"fetched_at": string,"http_status": number | null,"id": number,"is_complete": boolean,"run_id": string
                  }
                  Insert: {
                    "ats_source_id": string,"error"?: string | null,"fetch_day": string,"fetched_at"?: string,"http_status"?: number | null,"id"?: never,"is_complete"?: boolean,"run_id": string
                  }
                  Update: {
                    "ats_source_id"?: string,"error"?: string | null,"fetch_day"?: string,"fetched_at"?: string,"http_status"?: number | null,"id"?: never,"is_complete"?: boolean,"run_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ats_fetches_ats_source_id_fkey"
      columns: ["ats_source_id"]
isOneToOne: false
      referencedRelation: "ats_sources"
      referencedColumns: ["id"]
    }
                  ]
                },"ats_sources": {
                  Row: {
                    "board_key": string,"company_id": string,"id": string,"is_active": boolean,"kind": Database["public"]['Enums']["ats_kind"]
                  }
                  Insert: {
                    "board_key": string,"company_id": string,"id"?: string,"is_active"?: boolean,"kind": Database["public"]['Enums']["ats_kind"]
                  }
                  Update: {
                    "board_key"?: string,"company_id"?: string,"id"?: string,"is_active"?: boolean,"kind"?: Database["public"]['Enums']["ats_kind"]
                  }
                  Relationships: [
                    {
      foreignKeyName: "ats_sources_company_id_fkey"
      columns: ["company_id"]
isOneToOne: false
      referencedRelation: "companies"
      referencedColumns: ["id"]
    }
                  ]
                },"companies": {
                  Row: {
                    "careers_url": string,"created_at": string,"id": string,"name": string,"slug": string
                  }
                  Insert: {
                    "careers_url": string,"created_at"?: string,"id"?: string,"name": string,"slug": string
                  }
                  Update: {
                    "careers_url"?: string,"created_at"?: string,"id"?: string,"name"?: string,"slug"?: string
                  }
                  Relationships: [
                    
                  ]
                },"fetch_claims": {
                  Row: {
                    "claimed_at": string,"fetch_day": string,"url_key": string
                  }
                  Insert: {
                    "claimed_at"?: string,"fetch_day": string,"url_key": string
                  }
                  Update: {
                    "claimed_at"?: string,"fetch_day"?: string,"url_key"?: string
                  }
                  Relationships: [
                    
                  ]
                },"listing_program_rules": {
                  Row: {
                    "company_id": string,"id": string,"program_id": string,"title_regex": string
                  }
                  Insert: {
                    "company_id": string,"id"?: string,"program_id": string,"title_regex": string
                  }
                  Update: {
                    "company_id"?: string,"id"?: string,"program_id"?: string,"title_regex"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "listing_program_rules_company_id_fkey"
      columns: ["company_id"]
isOneToOne: false
      referencedRelation: "companies"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "listing_program_rules_program_id_fkey"
      columns: ["program_id"]
isOneToOne: false
      referencedRelation: "programs"
      referencedColumns: ["id"]
    }
                  ]
                },"listings": {
                  Row: {
                    "ats_source_id": string,"closed_at": string | null,"content_hash": string,"dedupe_key": string,"external_id": string,"first_seen_at": string,"id": string,"key_facts": NonNullable<Json>,"last_seen_at": string,"location": string | null,"posted_at": string | null,"program_id": string | null,"title": string,"url": string
                  }
                  Insert: {
                    "ats_source_id": string,"closed_at"?: string | null,"content_hash": string,"dedupe_key": string,"external_id": string,"first_seen_at"?: string,"id"?: string,"key_facts"?: NonNullable<Json>,"last_seen_at"?: string,"location"?: string | null,"posted_at"?: string | null,"program_id"?: string | null,"title": string,"url": string
                  }
                  Update: {
                    "ats_source_id"?: string,"closed_at"?: string | null,"content_hash"?: string,"dedupe_key"?: string,"external_id"?: string,"first_seen_at"?: string,"id"?: string,"key_facts"?: NonNullable<Json>,"last_seen_at"?: string,"location"?: string | null,"posted_at"?: string | null,"program_id"?: string | null,"title"?: string,"url"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "listings_ats_source_id_fkey"
      columns: ["ats_source_id"]
isOneToOne: false
      referencedRelation: "ats_sources"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "listings_program_id_fkey"
      columns: ["program_id"]
isOneToOne: false
      referencedRelation: "programs"
      referencedColumns: ["id"]
    }
                  ]
                },"metrics_events": {
                  Row: {
                    "event": string,"id": number,"occurred_at": string,"props": NonNullable<Json>,"run_id": string | null,"source": string,"subject_id": string | null,"subject_type": string | null,"user_ref": string | null,"value": number | null
                  }
                  Insert: {
                    "event": string,"id"?: never,"occurred_at"?: string,"props"?: NonNullable<Json>,"run_id"?: string | null,"source": string,"subject_id"?: string | null,"subject_type"?: string | null,"user_ref"?: string | null,"value"?: number | null
                  }
                  Update: {
                    "event"?: string,"id"?: never,"occurred_at"?: string,"props"?: NonNullable<Json>,"run_id"?: string | null,"source"?: string,"subject_id"?: string | null,"subject_type"?: string | null,"user_ref"?: string | null,"value"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "metrics_events_run_id_fkey"
      columns: ["run_id"]
isOneToOne: false
      referencedRelation: "pipeline_runs"
      referencedColumns: ["id"]
    }
                  ]
                },"pipeline_runs": {
                  Row: {
                    "counts": NonNullable<Json>,"finished_at": string | null,"gh_run_id": string | null,"id": string,"job": string,"started_at": string,"status": string
                  }
                  Insert: {
                    "counts"?: NonNullable<Json>,"finished_at"?: string | null,"gh_run_id"?: string | null,"id"?: string,"job": string,"started_at"?: string,"status"?: string
                  }
                  Update: {
                    "counts"?: NonNullable<Json>,"finished_at"?: string | null,"gh_run_id"?: string | null,"id"?: string,"job"?: string,"started_at"?: string,"status"?: string
                  }
                  Relationships: [
                    
                  ]
                },"profiles": {
                  Row: {
                    "citizenship": Database["public"]['Enums']["citizenship"] | null,"created_at": string,"degree_level": Database["public"]['Enums']["degree_level"] | null,"disciplines": (string)[],"email_alerts": boolean,"expected_graduation": string | null,"is_double_degree": boolean,"planning_honours": boolean,"university": string | null,"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "citizenship"?: Database["public"]['Enums']["citizenship"] | null,"created_at"?: string,"degree_level"?: Database["public"]['Enums']["degree_level"] | null,"disciplines"?: (string)[],"email_alerts"?: boolean,"expected_graduation"?: string | null,"is_double_degree"?: boolean,"planning_honours"?: boolean,"university"?: string | null,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "citizenship"?: Database["public"]['Enums']["citizenship"] | null,"created_at"?: string,"degree_level"?: Database["public"]['Enums']["degree_level"] | null,"disciplines"?: (string)[],"email_alerts"?: boolean,"expected_graduation"?: string | null,"is_double_degree"?: boolean,"planning_honours"?: boolean,"university"?: string | null,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    
                  ]
                },"program_follows": {
                  Row: {
                    "created_at": string,"notify": boolean,"program_id": string,"user_id": string
                  }
                  Insert: {
                    "created_at"?: string,"notify"?: boolean,"program_id": string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"notify"?: boolean,"program_id"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "program_follows_program_id_fkey"
      columns: ["program_id"]
isOneToOne: false
      referencedRelation: "programs"
      referencedColumns: ["id"]
    }
                  ]
                },"program_window_events": {
                  Row: {
                    "actor": Database["public"]['Enums']["provenance"],"after": NonNullable<Json>,"before": Json | null,"event_type": string,"extraction_id": string | null,"id": number,"occurred_at": string,"program_window_id": string
                  }
                  Insert: {
                    "actor": Database["public"]['Enums']["provenance"],"after": NonNullable<Json>,"before"?: Json | null,"event_type": string,"extraction_id"?: string | null,"id"?: never,"occurred_at"?: string,"program_window_id": string
                  }
                  Update: {
                    "actor"?: Database["public"]['Enums']["provenance"],"after"?: NonNullable<Json>,"before"?: Json | null,"event_type"?: string,"extraction_id"?: string | null,"id"?: never,"occurred_at"?: string,"program_window_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "program_window_events_program_window_id_fkey"
      columns: ["program_window_id"]
isOneToOne: false
      referencedRelation: "program_windows"
      referencedColumns: ["id"]
    }
                  ]
                },"program_windows": {
                  Row: {
                    "closes_on": string | null,"closes_precision": Database["public"]['Enums']["date_precision"] | null,"created_at": string,"cycle_year": number,"first_observed_open_at": string | null,"id": string,"last_verified_at": string | null,"opens_on": string | null,"opens_precision": Database["public"]['Enums']["date_precision"] | null,"program_ends_on": string | null,"program_id": string,"program_starts_on": string | null,"provenance": Database["public"]['Enums']["provenance"],"source_url": string,"status": Database["public"]['Enums']["window_status"],"updated_at": string,"window_seq": number
                  }
                  Insert: {
                    "closes_on"?: string | null,"closes_precision"?: Database["public"]['Enums']["date_precision"] | null,"created_at"?: string,"cycle_year": number,"first_observed_open_at"?: string | null,"id"?: string,"last_verified_at"?: string | null,"opens_on"?: string | null,"opens_precision"?: Database["public"]['Enums']["date_precision"] | null,"program_ends_on"?: string | null,"program_id": string,"program_starts_on"?: string | null,"provenance": Database["public"]['Enums']["provenance"],"source_url": string,"status"?: Database["public"]['Enums']["window_status"],"updated_at"?: string,"window_seq"?: number
                  }
                  Update: {
                    "closes_on"?: string | null,"closes_precision"?: Database["public"]['Enums']["date_precision"] | null,"created_at"?: string,"cycle_year"?: number,"first_observed_open_at"?: string | null,"id"?: string,"last_verified_at"?: string | null,"opens_on"?: string | null,"opens_precision"?: Database["public"]['Enums']["date_precision"] | null,"program_ends_on"?: string | null,"program_id"?: string,"program_starts_on"?: string | null,"provenance"?: Database["public"]['Enums']["provenance"],"source_url"?: string,"status"?: Database["public"]['Enums']["window_status"],"updated_at"?: string,"window_seq"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "program_windows_program_id_fkey"
      columns: ["program_id"]
isOneToOne: false
      referencedRelation: "programs"
      referencedColumns: ["id"]
    }
                  ]
                },"programs": {
                  Row: {
                    "cities": (string)[],"company_id": string,"created_at": string,"disciplines": (string)[],"eligibility_rules": NonNullable<Json>,"eligibility_rules_version": number,"eligibility_verified_at": string | null,"id": string,"is_published": boolean,"name": string,"program_type": Database["public"]['Enums']["program_type"],"slug": string,"source_url": string,"updated_at": string
                  }
                  Insert: {
                    "cities"?: (string)[],"company_id": string,"created_at"?: string,"disciplines"?: (string)[],"eligibility_rules"?: NonNullable<Json>,"eligibility_rules_version"?: number,"eligibility_verified_at"?: string | null,"id"?: string,"is_published"?: boolean,"name": string,"program_type": Database["public"]['Enums']["program_type"],"slug": string,"source_url": string,"updated_at"?: string
                  }
                  Update: {
                    "cities"?: (string)[],"company_id"?: string,"created_at"?: string,"disciplines"?: (string)[],"eligibility_rules"?: NonNullable<Json>,"eligibility_rules_version"?: number,"eligibility_verified_at"?: string | null,"id"?: string,"is_published"?: boolean,"name"?: string,"program_type"?: Database["public"]['Enums']["program_type"],"slug"?: string,"source_url"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "programs_company_id_fkey"
      columns: ["company_id"]
isOneToOne: false
      referencedRelation: "companies"
      referencedColumns: ["id"]
    }
                  ]
                },"rate_limits": {
                  Row: {
                    "hits": number,"key": string,"window_start": string
                  }
                  Insert: {
                    "hits"?: number,"key": string,"window_start": string
                  }
                  Update: {
                    "hits"?: number,"key"?: string,"window_start"?: string
                  }
                  Relationships: [
                    
                  ]
                },"resumes": {
                  Row: {
                    "archived_at": string | null,"created_at": string,"id": string,"iv": string,"kek_version": number,"label": string,"mime_type": string,"sha256": string,"size_bytes": number,"storage_path": string,"user_id": string,"version": number,"wrapped_dek": string
                  }
                  Insert: {
                    "archived_at"?: string | null,"created_at"?: string,"id"?: string,"iv": string,"kek_version": number,"label": string,"mime_type": string,"sha256": string,"size_bytes": number,"storage_path": string,"user_id": string,"version": number,"wrapped_dek": string
                  }
                  Update: {
                    "archived_at"?: string | null,"created_at"?: string,"id"?: string,"iv"?: string,"kek_version"?: number,"label"?: string,"mime_type"?: string,"sha256"?: string,"size_bytes"?: number,"storage_path"?: string,"user_id"?: string,"version"?: number,"wrapped_dek"?: string
                  }
                  Relationships: [
                    
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "is_admin":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"log_event":
{ Args: { "event": string,"props"?: Json }; Returns: undefined
                           },
"purge_rate_limits":
{ Args: Record<PropertyKey, never>; Returns: number
                           },
"rate_limit_hit":
{ Args: { "bucket": string,"max_hits": number,"window_len": string }; Returns: boolean
                           }
          }
          Enums: {
            "app_status": "saved"|"applied"|"online_assessment"|"interview"|"offer"|"rejected","ats_kind": "greenhouse"|"lever"|"workday","citizenship": "au_citizen"|"au_pr"|"nz_citizen"|"intl_student"|"other","date_precision": "day"|"month"|"estimated","degree_level": "undergraduate"|"honours"|"masters_coursework"|"masters_research"|"phd","program_type": "internship"|"vacationer"|"graduate"|"cadetship"|"discovery","provenance": "seed"|"ats"|"monitor"|"admin","window_status": "upcoming"|"open"|"closed"|"unknown"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "app_status": ["saved", "applied", "online_assessment", "interview", "offer", "rejected"],"ats_kind": ["greenhouse", "lever", "workday"],"citizenship": ["au_citizen", "au_pr", "nz_citizen", "intl_student", "other"],"date_precision": ["day", "month", "estimated"],"degree_level": ["undergraduate", "honours", "masters_coursework", "masters_research", "phd"],"program_type": ["internship", "vacationer", "graduate", "cadetship", "discovery"],"provenance": ["seed", "ats", "monitor", "admin"],"window_status": ["upcoming", "open", "closed", "unknown"]
          }
        }
} as const

