// Generate TypeScript types from the local database, or check the committed ones are current.
//
//   node scripts/types.mjs --write   regenerate apps/web/src/server/db/database.types.ts
//   node scripts/types.mjs --check   exit 1 if the committed file differs from a fresh one
//
// Needs the local Supabase stack running with every migration applied (`pnpm db:start`), so a
// migration that changes a table without regenerating the types fails CI here.

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath, URL } from "node:url";

const OUTPUT = fileURLToPath(
  new URL("../../../apps/web/src/server/db/database.types.ts", import.meta.url),
);
const WORKDIR = fileURLToPath(new URL("..", import.meta.url));

// Never edited by hand: the check below fails if it differs from a fresh generation.
const HEADER = "// Generated by `pnpm --filter @internradar/db types:write`. Do not edit.\n";

// Line endings differ by platform; compare content, not Windows versus Linux.
const normalise = (text) => text.replace(/\r\n/g, "\n");

function generate() {
  // One fixed command, no user input. cwd, not --workdir, so a path with a space is safe.
  const output = execSync("pnpm exec supabase gen types typescript --local --schema public", {
    cwd: WORKDIR,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  return HEADER + normalise(output);
}

const say = (text) => process.stdout.write(`${text}\n`);
const complain = (text) => process.stderr.write(`${text}\n`);

const mode = process.argv[2];

if (mode === "--write") {
  writeFileSync(OUTPUT, generate());
  say(`wrote ${OUTPUT}`);
} else if (mode === "--check") {
  const committed = normalise(readFileSync(OUTPUT, "utf8"));
  if (committed === generate()) {
    say("database types are up to date");
  } else {
    complain("database.types.ts is out of date: run `pnpm --filter @internradar/db types:write`");
    process.exitCode = 1;
  }
} else {
  complain("usage: node scripts/types.mjs --write | --check");
  process.exitCode = 2;
}
